(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(autopair-global-mode t)
 '(backup-directory-alist (quote ((".*" . "~/.emacs.d/backups/"))))
 '(column-number-mode t)
 '(custom-safe-themes (quote ("381c92f4ee13b5ffe4e269a8b5cbf763faf1c9ea" "517aecb1202bfa31fd3c44473d72483c5166124d" default)))
 '(dabbrev-case-fold-search nil)
 '(desktop-save-mode nil)
 '(diff-switches "-u")
 '(enable-recursive-minibuffers t)
 '(erc-hide-list (quote ("JOIN" "NICK" "PART" "QUIT")))
 '(erc-nick "alfborge")
 '(find-grep-options "-q  --exclude=\"*.svn-base\" --exclude=\"*~\" --exclude=\"*.pyc\"")
 '(hl-needed-mode t)
 '(hl-needed-on-config-change nil)
 '(ido-create-new-buffer (quote never))
 '(ido-enable-flex-matching t)
 '(ido-enable-last-directory-history nil)
 '(ido-enable-regexp nil)
 '(ido-max-directory-size 300000)
 '(ido-max-file-prompt-width 0.1)
 '(ido-use-filename-at-point (quote guess))
 '(ido-use-url-at-point t)
 '(ido-use-virtual-buffers t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(line-number-mode t)
 '(mark-even-if-inactive t)
 '(menu-bar-mode nil)
 '(mumamo-chunk-coloring 5)
 '(ns-alternate-modifier (quote super))
 '(ns-command-modifier (quote meta))
 '(ns-right-alternate-modifier nil)
 '(ns-right-command-modifier (quote super))
 '(org-agenda-files (quote ("/Users/alf.lervag/Dropbox/.settings/emacs.d/scripts/journal.org" "/Users/alf.lervag/Dropbox/.settings/emacs.d/scripts/projects.org")))
 '(org-agenda-ndays 7)
 '(org-agenda-show-all-dates t)
 '(org-agenda-skip-deadline-if-done t)
 '(org-agenda-skip-scheduled-if-done t)
 '(org-agenda-start-on-weekday nil)
 '(org-deadline-warning-days 14)
 '(savehist-mode t)
 '(scroll-bar-mode nil)
 '(server-mode t)
 '(set-mark-command-repeat-pop t)
 '(tool-bar-mode nil)
 '(transient-mark-mode nil)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(vc-bzr-log-switches "--include-merges"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(diff-added ((t (:foreground "#728a05" :inverse-video t))))
 '(diff-changed ((t (:foreground "#a57705" :inverse-video t))))
 '(diff-context ((((background dark)) (:foreground "White")) (t (:foreground "Black"))))
 '(diff-hunk-header ((((background dark)) (:foreground "Black" :background "#05057F7F8D8D")) (t (:foreground "White" :background "Salmon"))))
 '(diff-index ((((background dark)) (:foreground "Magenta")) (t (:foreground "Green"))))
 '(diff-indicator-added ((((background dark)) (:foreground "#111117175555" :background "#7474FFFF7474")) (t nil)))
 '(diff-indicator-removed ((((background dark)) (:foreground "#111117175555" :background "#FFFF9B9BFFFF")) (t nil)))
 '(diff-nonexistent ((((background dark)) (:foreground "#FFFFFFFF7474")) (t (:foreground "DarkBlue"))))
 '(diff-removed ((t (:foreground "#c60007" :inverse-video t))))
 '(highlight ((t (:background "#0a2832"))))
 '(org-hide ((t (:foreground "#042028")))))
