(require-package 'evil)
(require 'evil)
(evil-mode 1)
(key-chord-define evil-insert-state-map "jj" 'evil-normal-state)
(define-key evil-insert-state-map (kbd "C-SPC") 'evil-normal-state)

(add-hook 'org-capture-mode-hook 'evil-emacs-state)
(add-hook 'org-capture-prepare-finalize-hook 'evil-normal-state)
(evil-set-initial-state 'magit-process-mode 'emacs)
(evil-set-initial-state 'jira-mode 'emacs)
(evil-set-initial-state 'git-commit-mode 'emacs)
(evil-set-initial-state 'help-mode 'emacs)
(provide 'setup-evil)
